on: [push]

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: SFTP Deploy
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: SFTP Deploy
            uses: wlixcc/SFTP-Deploy-Action@v1.2.4
            with:
                username: ${{ secrets.IST_USERNAME }}
                server: ${{ secrets.IST_SERVER }}
                port: 22
                local_path: './'
                remote_path: './'
                sftp_only: true
                password: ${{ secrets.IST_HOSTING }}
